### PR TITLE
Improve bottom menu

### PR DESCRIPTION
**Pull request by hcarneiro**
Issue reference: https://github.com/Fliplet/fliplet-studio/issues/3428

Needs this to be deployed too: https://github.com/Fliplet/fliplet-theme-default/pull/40

### CODE REVIEW

**Comment by tonytlwu** [comment]
@hcarneiro Got a checklist for you below:

- [ ] It works on iPhone X
- [ ] It works on non-iPhone X
- [ ] It works in Studio on iPhone X
- [ ] It works in Studio on non-iPhone X

Also, if you remember, our attempts earlier on left a black container at the top because the background is set against the container, not the `ul` element. Does this mean the container is still sitting against the bottom (with a transparent background) and potentially blocking the content behind it? This could lead to users not able to tap and access their content and buttons.

**Comment by squallstar** [comment]
What about Android? That's where the issue was originally reported too.

**Comment by hcarneiro** [comment]
@squallstar @tonytlwu I'll test on Android, but I might need your help set up a FV on Android with access to Staging!

**Comment by hcarneiro** [comment]
@squallstar I can confirm that on Android the issue is also fixed.

**Pull request merged**
