### PR TITLE
[Fix] Ensures user is not able to target hidden menus with TAB

### PR DESCRIPTION
**Pull request by MaksymShokin**
@sofiiakvasnevska

## Issue
Fliplet/fliplet-studio#6420

## Description
Active will change the display from none to block.

## Backward compatibility
This change is fully backward compatible.

## Reviewers
@upplabs-alex-levchenko

### CODE REVIEW

**Comment by tonytlwu** [comment]
@MaksymShokin Can you add a screencast for how the menu expands and collapses before and after this change? I believe the opacities were used to facilitate a smooth animation.

**Comment by MaksymShokin** [comment]
@tonytlwu 
Bottom icon bar seems fine to me.
https://streamable.com/8l8xfn

**Comment by MaksymShokin** [comment]
Fixed. https://streamable.com/qn7dy8
First is staging, second is production

**Review by tonytlwu — APPROVED** [review]
@sofiiakvasnevska This is ready for testing

Risk: Low
Affected: Bottom bar menus
Verify: Menu opens and closes as expected using mouse, touch gesture and keyboard

**Pull request merged**
